[package]
name = "exact-openapi-gen"
version = "0.1.0"
authors = ["wildarch <daandegraaf9@gmail.com>"]

[dependencies]
select = "0.4"
reqwest = "0.7"
error-chain = "0.10"
openapi = { git = "https://github.com/softprops/openapi" }
